package com.devlopp.teq.service;

import java.util.ArrayList;
import java.util.List;

public abstract class Service {
    protected int id;
    protected int clientId;
    protected String postalCode;
    protected String language;
    protected String organizationType;
    protected String referredBy;
    protected String updateReason;
    protected String serviceType;
    protected List<String> essentialSkills = new ArrayList<>();
    protected List<String> supportServices = new ArrayList<>();
    protected List<String> targetGroups = new ArrayList<>();
    protected List<NewcomerChildCare> childCares = new ArrayList<>();

    /**
     * Returns the unique identifier of this service generated by the database.
     * 
     * @return ID of this service
     */
    public int getId() {
        return id;
    }

    /**
     * Returns the ID of the client using this service.
     * 
     * @return ID of the client
     */
    public int getClientId() {
        return clientId;
    }

    /**
     * Returns the postal code of where this service was offered.
     * 
     * @return postal code of this service
     */
    public String getPostalCode() {
        return postalCode;
    }

    /**
     * Returns the language that this service is offered in.
     * 
     * @return language of this service
     */
    public String getLanguage() {
        return language;
    }

    /**
     * Returns the type of organization or institution where the client received
     * this service.
     * 
     * @return type of organization or institution where the client received this
     *         service
     */
    public String getOrganizationType() {
        return organizationType;
    }

    /**
     * Returns what had the client referred to this service.
     * 
     * @return what had the client referred to this service
     */
    public String getReferredBy() {
        return referredBy;
    }

    /**
     * Returns the reason for the update to this service's record.
     * 
     * @return reason for update of this service
     */
    public String getUpdateReason() {
        return updateReason;
    }

    /**
     * Returns the subtype discriminator that determines this service's type in the
     * database.
     * 
     * @return subtype discriminator for this service
     */
    public String getServiceType() {
        return serviceType;
    }

    /**
     * Returns a list of essential skills this service provided.
     * 
     * @return list of essential skills
     */
    public List<String> getEssentialSkills() {
        return essentialSkills;
    }

    /**
     * Adds an essential skill to this service.
     * 
     * @param essentialSkill essential skill
     */
    public void addEssentialSkill(String essentialSkill) {
        essentialSkills.add(essentialSkill);
    }

    /**
     * Returns a list of support services this service provided.
     * 
     * @return list of support services
     */
    public List<String> getSupportServices() {
        return supportServices;
    }

    /**
     * Adds a support service to this service.
     * 
     * @param supportService support service
     */
    public void addSupportService(String supportService) {
        supportServices.add(supportService);
    }

    /**
     * Returns a list of groups this service is targeted towards.
     * 
     * @return list of target groups
     */
    public List<String> getTargetGroups() {
        return targetGroups;
    }

    /**
     * Adds a target group to this service.
     * 
     * @param targetGroup target group
     */
    public void addTargetGroup(String targetGroup) {
        targetGroups.add(targetGroup);
    }

    /**
     * Returns a list of newcomer child care responses.
     * 
     * @return list of newcomer child care responses
     */
    public List<NewcomerChildCare> getNewcomerChildCare() {
        return childCares;
    }

    /**
     * Adds newcomer child care responses to this service.
     * 
     * @param childCare newcomer child care responses
     */
    public void addNewcomerChildCare(NewcomerChildCare childCare) {
        childCares.add(childCare);
    }
}
