package com.devlopp.teq.service;

import java.util.ArrayList;
import java.util.List;

public abstract class Service {
    protected int id;
    protected int clientId;
    protected String postalCode;
    protected String language;
    protected String organizationType;
    protected String referredBy;
    protected String updateReason;
    protected String serviceType;
    protected List<String> essentialSkills = new ArrayList<String>();
    protected List<String> supportServices = new ArrayList<String>();
    protected List<String> targetGroups = new ArrayList<String>();

    /**
     * Returns the unique identifier of this service generated by the database.
     * 
     * @return ID of this service
     */
    public int getId() {
        return id;
    }

    /**
     * Returns the ID of the client using this service.
     * 
     * @return ID of the client
     */
    public int getClientId() {
        return clientId;
    }

    /**
     * Returns the postal code of where this service was offered.
     * 
     * @return postal code of this service
     */
    public String getPostalCode() {
        return postalCode;
    }
    
    /**
     * Returns the language that this service is offered in.
     * 
     * @return language of this service
     */
    public String getLanguage() {
        return language;
    }

    /**
     * Returns the type of organization or institution where the client received this service.
     * 
     * @return type of organization or institution where the client received this service
     */
    public String getOrganizationType() {
        return organizationType;
    }

    /**
     * Returns what had the client referred to this service.
     * 
     * @return what had the client referred to this service
     */
    public String getReferredBy() {
        return referredBy;
    }

    /**
     * Returns the reason for the update to this service's record.
     * 
     * @return reason for update of this service
     */
    public String getUpdateReason() {
        return updateReason;
    }

    /**
     * Returns the subtype discriminator that determines this service's type in the database.
     * 
     * @return subtype discriminator for this service
     */
    public String getServiceType() {
        return serviceType;
    }

    /**
     * Returns a list of essential skills this service provided.
     * 
     * @return list of essential skills
     */
    public List<String> getEssentialSkills() {
        return essentialSkills;
    }

    /**
     * Returns a list of support services this service provided.
     * 
     * @return list of support services
     */
    public List<String> getSupportServices() {
        return supportServices;
    }

    /**
     * Returns a list of groups this service is targeted towards.
     * 
     * @return list of target groups
     */
    public List<String> getTargetGroups() {
        return targetGroups;
    }
}
