CREATE TABLE Language (
    LanguageCode    CHAR(3) PRIMARY KEY NOT NULL,
    description VARCHAR(32) NOT NULL
);

INSERT INTO Language
    (LanguageCode, description)
VALUES
	('ENG', 'English'),
	('FRE', 'French'),
	('ADA', 'Ada'),
	('AFF', 'Affar'),
	('AFR', 'Afrikaans'),
	('AKA', 'Aka'),
	('AKN' 'Akan'),
	('AKL', 'Aklanon'),
	('AKR', 'Akra'),
	('ALB', 'Albanian'),
	('ASL', 'American Sign Language (ASL)'),
	('AMA', 'Amharic'),
	('ANU', 'Anuak (Anywa)'),
	('ARB', 'Arabic'),
	('ARN', 'Aran'),
	('ARM', 'Armenian'),
	('ASH', 'Ashanti'),
	('ASS', 'Assyrian'),
	('AZE', 'Azeri'),
	('BAM', 'Bambara'),
	('BAN',' Bantu'),
	('BAU', 'Baule'),
	('BEL', 'Belen'),
	('BEM', 'Bemba'),
	('BEN', 'Bengali'),
	('BEI', 'Beni'),
	('BNN', 'Benin'),
	('BER', 'Berber'),
	('BIC', 'Bicol'),
	('BIJ', 'Bijaiya'),
	('BIN', 'Bini'),
	('BIS', 'Bisaya'),
	('BIA', 'Bissa'),
	('BON', 'Bontok'),
	('BRA', 'Braille'),
	('BRE', 'Breton'),
	('BUL', 'Bulgarian'),
	('BUR', 'Burmese'),
	('BUS', 'Busan'),
	('BUO', 'Busango'),
	('CAN', 'Cantonese'),
	('CAT', 'Catalan'),
	('CEB', 'Cebuano'),
	('CHA', 'Chakma'),
	('CHD', 'Chaldean'),
	('CHO', 'Chaocho'),
	('CHV', 'Chavano'),
	('CHI', 'Chichewa'),
	('CHS', 'Chinese - Simplified (Translation Only)'),
	('CHT', 'Chinese - Traditional (TranslationOnly)'),
	('COW', 'Chiuchow'),
	('CYO', 'Chiyao'),
	('CWA', 'Chowchau'),
	('CON', 'Concani'),
	('CRE', 'Creole'),
	('CRO', 'Croatian'),
	('CZC', 'Czech'),
	('DAN', 'Danish'),
	('DAR', 'Dari' ),
	('DEF', 'Deaf-Mute'),
	('DIO', 'Dioula'),
	('DUT', 'Dutch'),
	('DZO', 'Dzongkha'),
	('EDO', 'Edo'),
	('EFI', 'Efik'),
	('EST', 'Estonian'),
	('EWE', 'Ewe'),
	('FAC', 'Facilitator'),
	('FAN', 'Fang'),
	('FNT', 'Fanti'),
	('FAR', 'Farsi (Persian)'),
	('FIN', 'Finnish'),
	('FLE', 'Flemish'),
	('FOO', 'Foochow'),
	('FOU', 'Fouki'),
	('FOL', 'Foullah'),
	('FUK', 'Fukinese'),
	('FUL', 'Fulani'),
	('GAA', 'Ga'),
	('GAE', 'Gaelic'),
	('GER', 'German'),
	('GRE', 'Greek'),
	('GUE', 'Guerze'),
	('GUJ', 'Gujarati'),
	('HAI', 'Hainam'),
	('HKC', 'Hakha Chin'),
	('HKK' 'Hakka'),
	('HAR', 'Harara'),
	('HRR', 'Harary'),
	('HGR', 'Hargar'),
	('HAS', 'Hassanya'),
	('HAU', 'Hausa'),
	('HEB', 'Hebrew'),
	('HIL', 'Hillgaynon'),
	('HIN', 'Hindi'),
	('HID', 'Hindko'),
	('HIN', 'Hokkin'),
	('HUN' , 'Hungarian'),
	('IBB', 'Ibibio'),
	('IBO', 'Ibo'),
	('ICE', 'Icelandic'),
	('IGO', 'Igorot'),
	('ILL', 'Ilongo'),
	('ILI', 'Ilican'),
	('IND', 'Indonesian'),
	('ISH', 'Ishan'),
	('ITA', 'Italian'),
	('IZI', 'Izi'),
	('JAP', 'Japanese'),
	('JAR', 'Jarai'),
	('JAV', 'Javanese'),
	('JOL', 'Jolay'),
	('KAC', 'Kacchi'),
	('KAK', 'Kakwa'),
	('KAN', 'Kanarese'),
	('KDA', 'Kandahari'),
	('KAK', 'Kankani'),
	('KAR', 'Karen'),
	('KAS', 'Kashmiri'),
	('KHM', 'Khmer'),
	('KIH', 'Kihavu'),
	('KIK', 'Kikongo'),
	('KIN', 'Kinyamulenge'),
	('KIA', 'Kinyarwanda'),
	('KIR', 'Kirundi'),
	('KIS', 'Kiswahili'),
	('KON','Konkani'),
	('KOR', 'Korean'),
	('KRI', 'Krio'),
	('KUR', 'Kurdish'),
	('LSQ', 'La langue des signes québécoise (LSQ)'),
	('LAO', 'Laotian'),
	('LAT', 'Latvian'),
	('LEB', 'Lebanese'),
	('LEN', 'Lengie'),
	('LIN', 'Lingala'),
	('LIT', 'Lithuanian'),
	('LOW', 'Lowna'),
	('LUG', 'Luganda'),
	('LUG', 'Lugishu'),
	('LUT', 'Lutoro'),
	('MAC', 'Macedonian'),
	('MAA', 'Macena'),
	('MAU', 'Macua'),
	('MAH', 'Mahou'),
	('MAK', 'Makonde'),
	('MAL', 'Malagasy'),
	('MLY', 'Malay'),
	('MAY', 'Malayalam'),
	('MGO', 'Maligo'),
	('MNK', 'Malinke'),
	('MAT',' Maltese'),
	('MAN', 'Mandarin'),
	('MNO', 'Mandingo'),
	('MAR', 'Marathi'),
	('MAS', 'Mashi'),
	('MEN', 'Mende'),
	('MIN', 'Mina' ),
	('MIZ', 'Mizo'),
	('MON', 'Mongolian'),
	('MOR', 'More'),
	('NEP', 'Nepali'),
	('NOR', 'Norwegian'),
	('NUE', 'Nuer'),
	('NZI', 'Nzima'),
	('OKP', 'Okpe'),
	('OYA', 'Oriya'),
	('ORO', 'Oromo'),
	('OSA', 'Osal'),
	('OAL', 'Other African Languages' ),
	('OCD', 'Other Chinese Dialects'),
	('OEL', 'Other European Languages'),
	('OLN', 'Other Languages Nes'),
	('OME', 'Other Middle Eastern Languages'),
	('OSL', 'Other Signed Languages' ),
	('OSA', 'Other South Asian Languages'),
	('OWH', 'Other Western Hemishphere Indian Languages'),
	('OTU', 'Otuho'),
	('PAH', 'Pahari'),
	('PAM', 'Pampango'),
	('PAS', 'Pashto'),
	('PEU', 'Peul'),
	('PHO', 'Phuockien'),
	('PID', 'Pidgin'),
	('PLA', 'Plautdietsch (Mennonite Low German)'),
	('POL', 'Polish'),
	('POR', 'Portuguese'),
	('POU', 'Poular'),
	('PUN', 'Punjabi'),
	('ROH', 'Rohingya'),
	('ROM', 'Romani'),
	('RAN', 'Romanian'),
	('RUK', 'Rukiga'),
	('RUN', 'Runyankole'),
	('RUS', 'Russian'),
	('RUT', 'Rutooro'),
	('SAM', 'Samoan'),
	('SAN', 'Sango'),
	('SCO', 'Scoula'),
	('SEC', 'Sechuan'),
	('SER', 'Serbian'),
	('SCB', 'Serbo-Croat-Bosnian'),
	('SES', 'Sesotho'),
	('SWI', 'Seswi'),
	('SEY', 'Seychelles'),
	('SHA', 'Shan'),
	('SHN', 'Shanghai'),
	('SAI', 'Shansai'),
	('SIN', 'Sindhi'),
	('SHI', 'Shansai'),
	('SDI', 'Sindhi'),
	('SHE', 'Sinhalese'),
	('SHO', 'Shona'),
	('SLO', 'Slovak'),
	('SOE', 'Slovene'),
	('SOM', 'Somali'),
	('SON', 'Soninke'),
	('SOT', 'Sotho'),
	('SOU', 'Soussou'),
	('STH', 'Sothern Burun'),
	('SPN', 'Spanish'),
	('SUE', 'Suesue'),
	('SUK', 'Sukama'),
	('SWA', 'Swahili'),
	('SZI', 'Swazai'),
	('SWE', 'Swedish'),
	('TAG', 'Tagalog'),
	('TAI', 'Taichew'),
	('TAM', 'Tamil'),
	('TAR', 'Tari'),
	('TAT', 'Tatar'),
	('TET', 'Tetshanese'),
	('TEL', 'Telugu'),
	('TEO', 'Teochew'),
	('THA', 'Thai'),
	('TIB', 'Tibetan'),
	('TIC', 'Tichiew'),
	('TIG', 'Tigrigna'),
	('TIM', 'Timini'),
	('TIV', 'Tiv'),
	('TOI', 'Toishan'),
	('TSH', 'Tshiluba'),
	('TWI', 'Twi'),
	('UHR', 'Uhrobo'),
	('ULG', 'Ulgrigma'),
	('UKR', 'Ukranoan'),
	('UMB', 'Umbundu'),
	('UNA', 'Unama'),
	('URD', 'Urdu'),
	('UZB', 'Uzbek'),
	('VIE', 'Vietnamese'),
	('VIS', 'Visayan'),
	('WAR', 'Waray'),
	('WEL', 'Welsh'),
	('WOL', 'Wolof'),
	('XHO', 'Xhosa'),
	('YIB', 'Yiboe'),
	('YID', 'Yiddish'),
	('YOR', 'Yoruba'),
	('ZSH', 'Zshiluba'),
	('ZUG', 'Zuganda'),
	('ZUL', 'Zulu');